language: cpp

env:
  global:
    - LANG="zh_CN.UTF-8"
  matrix:
    - TRAVIS_OS_NAME=osx CC=clang CXX=clang
    - TRAVIS_OS_NAME=osx CC=gcc CXX=gcc
    - TRAVIS_OS_NAME=linux CC=gcc CXX=gcc
    
before_script:
  - REPO_DIR=$PWD
  - mkdir -p tools && cd tools
  - CMAKE_PREFIX=$PWD/prebuilt/cmake
  - if [ ! -e "$CMAKE_PREFIX/bin/cmake" ]; then
        wget -c "https://github.com/Kitware/CMake/archive/v3.4.1.tar.gz" -O CMake-3.4.1.tar.gz ;
        tar -axvf CMake-3.4.1.tar.gz > build_cmake.log 2>&1 ;
        cd CMake-3.4.1 ;
        ./bootstrap --prefix=$CMAKE_PREFIX  >> build_cmake.log 2>&1 ;
        make -j4 install  >> build_cmake.log 2>&1 ;
    fi
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - $CMAKE_PREFIX/bin/cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ;

after_success:
  - test/coroutine_test
  
script: 
  - make -j4

install: true

cache: 
    apt: true
    directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
